name: MSVC

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 'Attempt to pull blob from cache'
        id: restore-blob
        uses: actions/cache/restore@v4
        with:
          path: "${{github.workspace}}/gtk-blob"
          key: ${{ runner.os }}-${{ runner.arch }}-blob
      - uses: actions/checkout@v4
        if: steps.restore-blob.outputs.cache-hit != 'true'
        with:
          path: gvsbuild
          repository: wingtk/gvsbuild
          ref: main
      - name: Install gvsbuild and deps
        if: steps.restore-blob.outputs.cache-hit != 'true'
        run: |
          python -m pip install wheel build
          python -m pip install .
        working-directory: gvsbuild
      - name: Move git binary
        if: steps.restore-blob.outputs.cache-hit != 'true'
        # Temporarily move preinstalled git to prevent errors related to cygwin.
        run: Rename-Item "C:\Program Files\Git\usr\bin" notbin
      - name: Build
        if: steps.restore-blob.outputs.cache-hit != 'true'
        run: >
          gvsbuild build
          --patches-root-dir=${{ github.workspace }}\gvsbuild\gvsbuild\patches
          gtk3 gtksourceview4 hicolor-icon-theme adwaita-icon-theme
        working-directory: gvsbuild
      - name: Restore git binary
        if: steps.restore-blob.outputs.cache-hit != 'true'
        run: Rename-Item  "C:\Program Files\Git\usr\notbin" bin
      - name: Zip Bundle
        if: steps.restore-blob.outputs.cache-hit != 'true'
        run: |
          New-Item ${{ github.workspace }}\gtk-blob -ItemType Directory
          7z a ${{ github.workspace }}\gtk-blob\gtk-blob.zip "C:\gtk-build\gtk\x64\release"
      - name: 'Push blob to cache'
        if: steps.restore-blob.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore-blob.outputs.cache-primary-key }}
          path: "${{github.workspace}}/gtk-blob"
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: "${{github.workspace}}/gtk-blob/gtk-blob.zip"
      - name: 'Extract blob'
        run: 7z x ${{github.workspace}}/gtk-blob/gtk-blob.zip -oC:\gtk -y
      - name: Set up env
        run: |
          Write-Output "PKG_CONFIG=C:\gtk\release\bin\pkgconf.exe" >> $env:GITHUB_ENV
          Write-Output "XDG_DATA_HOME=$HOME\.local\share" >> $env:GITHUB_ENV
          Write-Output "C:\gtk\release\bin" >> $env:GITHUB_PATH
      - uses: actions/checkout@v4
      - name: 'Build Xournal++'
        uses: ./.github/actions/build
        with:
          build_type: RelWithDebInfo
          cmake_flags: '-DENABLE_GTEST=ON -DDOWNLOAD_GTEST=on -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl'
          shell: pwsh
      - name: 'Run tests'
        shell: msys2 {0}
        run: |
          cmake --build . --target test-units
          CI=true ./test/test-units
        working-directory: ${{github.workspace}}/build
