name: MSVC

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 'Attempt to pull blob from cache'
        id: restore-blob
        uses: actions/cache/restore@v4
        with:
          path: "${{github.workspace}}/build-dir"
          key: ${{ runner.os }}-${{ runner.arch }}-blob-poppler
      - uses: actions/checkout@v4
        with:
          path: gvsbuild
          repository: bhennion/gvsbuild
          ref: main
      - name: Install gvsbuild and deps
        run: |
          python -m pip install wheel build
          python -m pip install .
        working-directory: gvsbuild
      - name: Move git binary
        # Temporarily move preinstalled git to prevent errors related to cygwin.
        run: Rename-Item "C:\Program Files\Git\usr\bin" notbin
      - name: Build deps
        run: >
          gvsbuild build
          --build-dir=${{ github.workspace }}\build-dir
          --fast-build
          --patches-root-dir=${{ github.workspace }}\gvsbuild\gvsbuild\patches
          freetype glib libjpeg-turbo zlib libtiff-4 cairo fontconfig
        working-directory: gvsbuild
      - name: 'Push blob to cache'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore-blob.outputs.cache-primary-key }}
          path: "${{github.workspace}}/build-dir"
      - name: Build poppler
        run: >
          gvsbuild build
          --build-dir=${{ github.workspace }}\build-dir
          --patches-root-dir=${{ github.workspace }}\gvsbuild\gvsbuild\patches
          poppler
        working-directory: gvsbuild
