name: MSVC3

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          path: gvsbuild
          repository: bhennion/gvsbuild
          ref: add-xournalpp-deps
      - name: Install gvsbuild and deps
        run: |
          python -m pip install wheel build
          python -m pip install .
        working-directory: gvsbuild
      - name: Move git binary
        # Temporarily move preinstalled git to prevent errors related to cygwin.
        run: Rename-Item "C:\Program Files\Git\usr\bin" notbin
      - name: Build deps
        run: >
          gvsbuild build
          --build-dir=D:\gtk-build
          --debug
          --fast-build
          --patches-root-dir=${{ github.workspace }}\gvsbuild\gvsbuild\patches
          portaudio libzip
        working-directory: gvsbuild
      - name: Restore git binary
        run: Rename-Item  "C:\Program Files\Git\usr\notbin" bin
      - name: 'Publish'
        uses: actions/upload-artifact@v4
        with:
          name: "output"
          path: "D:/gtk-build/gtk/x64/release"
          if-no-files-found: error
